const SNACKBAR_SUCCESS = "SNACKBAR_SUCCESS";
const SNACKBAR_ERROR = "SNACKBAR_ERROR";
const SNACKBAR_CLEAR = "SNACKBAR_CLEAR";
const SNACKBAR_WARNING = "SNACKBAR_WARNING";
const SNACKBAR_INFO = "SNACKBAR_INFO";

const UITYPES = {
  SNACKBAR_SUCCESS,
  SNACKBAR_ERROR,
  SNACKBAR_CLEAR,
  SNACKBAR_WARNING,
  SNACKBAR_INFO,
};

export default UITYPES;
